import type {
  OverviewStatsResponse,
  MemoryAnalyticsResponse,
  FailureAnalyticsResponse,
} from "@/types/api";
import type { Opportunity, RetrievalEpisode } from "@/types/database";

export const MOCK_OVERVIEW_STATS: OverviewStatsResponse = {
  total_records_imported: 142,
  total_relevant_episodes: 52,
  total_excluded_records: 90,
  platform_distribution: [
    { platform: "Reddit (r/googlephotos)", count: 58, percentage: 40.8 },
    { platform: "Google Support Community", count: 48, percentage: 33.8 },
    { platform: "Twitter / X Discourse", count: 24, percentage: 16.9 },
    { platform: "Direct User Research", count: 12, percentage: 8.5 },
  ],
  item_type_distribution: [
    { item_type: "single_photo", count: 24, percentage: 46.2 },
    { item_type: "photo_set", count: 14, percentage: 26.9 },
    { item_type: "screenshot", count: 8, percentage: 15.4 },
    { item_type: "document", count: 4, percentage: 7.7 },
    { item_type: "video", count: 2, percentage: 3.8 },
  ],
  outcome_distribution: [
    { outcome: "failure", count: 28, percentage: 53.8 },
    { outcome: "partial_success", count: 14, percentage: 26.9 },
    { outcome: "success", count: 7, percentage: 13.5 },
    { outcome: "abandoned", count: 3, percentage: 5.8 },
  ],
  collection_batches: [
    {
      id: "batch-001",
      platform: "Reddit",
      collection_date: "2026-09-15T10:00:00Z",
      collection_method: "search_api",
      language: "en",
      date_range_start: null,
      date_range_end: null,
      records_found: 60,
      search_query: "can't find photo google photos search",
      records_imported: 58,
      relevant_records: 22,
      created_at: "2026-09-15T10:00:00Z",
      notes: "Extracted from top retrieval complaint threads on r/googlephotos",
    },
    {
      id: "batch-002",
      platform: "Google Support Community",
      collection_date: "2026-09-18T14:30:00Z",
      collection_method: "forum_scrape",
      language: "en",
      date_range_start: null,
      date_range_end: null,
      records_found: 50,
      search_query: "search not finding old picture album",
      records_imported: 48,
      relevant_records: 18,
      created_at: "2026-09-18T14:30:00Z",
      notes: "Support tickets tagged under Search & Discovery failures",
    },
    {
      id: "batch-003",
      platform: "Twitter / X Discourse",
      collection_date: "2026-09-21T09:15:00Z",
      collection_method: "keyword_stream",
      language: "en",
      date_range_start: null,
      date_range_end: null,
      records_found: 30,
      search_query: "google photos search missing receipt screenshot",
      records_imported: 24,
      relevant_records: 8,
      created_at: "2026-09-21T09:15:00Z",
      notes: "Public user grievances regarding visual OCR and receipt retrieval",
    },
    {
      id: "batch-004",
      platform: "Direct User Research",
      collection_date: "2026-09-24T16:00:00Z",
      collection_method: "interviews",
      language: "en",
      date_range_start: null,
      date_range_end: null,
      records_found: 12,
      search_query: "semi-structured interview transcripts",
      records_imported: 12,
      relevant_records: 4,
      created_at: "2026-09-24T16:00:00Z",
      notes: "Targeted interviews on temporal recollection vs algorithmic search",
    },
  ],
  latest_validation: {
    run_date: "2026-09-28T18:00:00Z",
    holdout_f1: 0.912,
    holdout_precision: 0.935,
    holdout_recall: 0.891,
    episode_count_agreement: 0.942,
  },
};

export const MOCK_MEMORY_ANALYTICS: MemoryAnalyticsResponse = {
  clue_frequencies: [
    { category: "visual_content", count: 42, percentage: 80.8 },
    { category: "time_temporal", count: 38, percentage: 73.1 },
    { category: "location_place", count: 29, percentage: 55.8 },
    { category: "social_context", count: 24, percentage: 46.2 },
    { category: "activity_action", count: 19, percentage: 36.5 },
    { category: "associated_text", count: 14, percentage: 26.9 },
    { category: "emotional_context", count: 11, percentage: 21.2 },
    { category: "medium_format", count: 9, percentage: 17.3 },
  ],
  forgotten_frequencies: [
    { category: "exact_date_or_year", count: 36, percentage: 69.2 },
    { category: "specific_location_name", count: 27, percentage: 51.9 },
    { category: "file_name_or_source", count: 22, percentage: 42.3 },
    { category: "device_used_to_capture", count: 18, percentage: 34.6 },
    { category: "whether_photo_or_screenshot", count: 12, percentage: 23.1 },
  ],
  clue_forgotten_cooccurrence: [
    { clue: "time_temporal", forgotten: "exact_date_or_year", count: 32 },
    { clue: "visual_content", forgotten: "exact_date_or_year", count: 28 },
    { clue: "location_place", forgotten: "specific_location_name", count: 22 },
    { clue: "social_context", forgotten: "exact_date_or_year", count: 19 },
    { clue: "associated_text", forgotten: "file_name_or_source", count: 12 },
  ],
  workaround_distribution: [
    { workaround_type: "manual_timeline_scrolling", count: 33, percentage: 63.5 },
    { workaround_type: "external_messaging_search", count: 18, percentage: 34.6 },
    { workaround_type: "asking_friends_family", count: 14, percentage: 26.9 },
    { workaround_type: "third_party_gallery_app", count: 9, percentage: 17.3 },
    { workaround_type: "re_photographing_or_giving_up", count: 8, percentage: 15.4 },
  ],
};

export const MOCK_FAILURE_ANALYSIS: FailureAnalyticsResponse = {
  failure_distribution: [
    { failure_type: "vocabulary_mismatch", count: 19, percentage: 36.5 },
    { failure_type: "temporal_ambiguity", count: 14, percentage: 26.9 },
    { failure_type: "ocr_text_inability", count: 8, percentage: 15.4 },
    { failure_type: "entity_misalignment", count: 6, percentage: 11.5 },
    { failure_type: "contextual_event_gap", count: 5, percentage: 9.6 },
  ],
  failure_by_item_type: [
    { item_type: "single_photo", failure_type: "vocabulary_mismatch", count: 11 },
    { item_type: "single_photo", failure_type: "temporal_ambiguity", count: 8 },
    { item_type: "photo_set", failure_type: "temporal_ambiguity", count: 6 },
    { item_type: "screenshot", failure_type: "ocr_text_inability", count: 6 },
    { item_type: "document", failure_type: "ocr_text_inability", count: 2 },
    { item_type: "single_photo", failure_type: "entity_misalignment", count: 5 },
  ],
  clue_failure_flow: [
    { clue_category: "time_temporal", failure_type: "temporal_ambiguity", outcome: "failure", count: 12 },
    { clue_category: "visual_content", failure_type: "vocabulary_mismatch", outcome: "failure", count: 14 },
    { clue_category: "associated_text", failure_type: "ocr_text_inability", outcome: "failure", count: 7 },
    { clue_category: "social_context", failure_type: "entity_misalignment", outcome: "partial_success", count: 4 },
  ],
};

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-01",
    title: "Episodic Milestone & Life-Event Temporal Anchoring",
    retrieval_scenario: "User seeks photos from an autobiographical life stage without knowing the exact calendar year.",
    target_type: "photo_set",
    remembered_info_summary: "Life events, approximate relative sequence, co-present people",
    forgotten_info_summary: "Exact calendar year, month, or timestamp",
    failure_stage: "query_formulation",
    observed_behavior: "Users try keyword queries with guessed years, fail, and resort to 30+ minutes of manual timeline scrolling.",
    current_workaround: "manual_timeline_scrolling",
    typical_outcome: "failure",
    supporting_episode_count: 24,
    total_relevant_episodes: 52,
    dataset_percentage: 46.2,
    source_diversity: 4,
    failure_rate: 62.5,
    failure_rate_denominator: 24,
    abandonment_rate: 12.5,
    abandonment_rate_denominator: 24,
    multi_attempt_rate: 79.2,
    multi_attempt_denominator: 24,
    workaround_rate: 70.8,
    manual_scroll_rate: 58.3,
    unknown_outcome_count: 2,
    evidence_strength: "strong",
    observed_consequence: "High user frustration and abandonment of personal discovery memories.",
    root_cause_hypothesis: "Calendar indexing does not mirror episodic autobiographical memory hierarchy.",
    alternative_explanations: "Users might misremember photo ownership across devices.",
    potential_ai_leverage: "Clustering and labeling life chapters from geo-temporal density transitions.",
    uncertainty: "Privacy concerns around automated life-milestone labeling.",
    generated_at: "2026-09-28T00:00:00Z",
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
  },
  {
    id: "opp-02",
    title: "Associative Multi-Clue Constraint Relaxation Engine",
    retrieval_scenario: "User inputs compound visual clues where one remembered detail is slightly inaccurate.",
    target_type: "single_photo",
    remembered_info_summary: "Multiple visual facets (color, object, outdoor setting, season)",
    forgotten_info_summary: "Exact object color or specific backdrop",
    failure_stage: "retrieval_execution",
    observed_behavior: "Exact-match conjunction returns 0 results because one adjective was incorrect.",
    current_workaround: "trial_and_error_query_refinement",
    typical_outcome: "failure",
    supporting_episode_count: 19,
    total_relevant_episodes: 52,
    dataset_percentage: 36.5,
    source_diversity: 4,
    failure_rate: 73.7,
    failure_rate_denominator: 19,
    abandonment_rate: 15.8,
    abandonment_rate_denominator: 19,
    multi_attempt_rate: 84.2,
    multi_attempt_denominator: 19,
    workaround_rate: 68.4,
    manual_scroll_rate: 52.6,
    unknown_outcome_count: 1,
    evidence_strength: "strong",
    observed_consequence: "User assumes photo was deleted and suffers search fatigue.",
    root_cause_hypothesis: "Strict boolean AND ranking penalizes partially inaccurate human recollections.",
    alternative_explanations: "Index missing visual concepts.",
    potential_ai_leverage: "Soft weighted vector similarity ranking across individual semantic slots.",
    uncertainty: "Potential precision drop if relaxation threshold is too permissive.",
    generated_at: "2026-09-28T00:00:00Z",
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
  },
  {
    id: "opp-03",
    title: "Screenshot & Document Semantic Content Extraction",
    retrieval_scenario: "User searches for information captured in a screenshot, receipt, or handwritten note.",
    target_type: "screenshot",
    remembered_info_summary: "Functional text content, purpose of screenshot, rough month",
    forgotten_info_summary: "Visual typography layout, exact spelling, source app",
    failure_stage: "indexing_extraction",
    observed_behavior: "OCR fails on low contrast, cursive handwriting, or rotated crops.",
    current_workaround: "external_messaging_search",
    typical_outcome: "failure",
    supporting_episode_count: 12,
    total_relevant_episodes: 52,
    dataset_percentage: 23.1,
    source_diversity: 3,
    failure_rate: 66.7,
    failure_rate_denominator: 12,
    abandonment_rate: 8.3,
    abandonment_rate_denominator: 12,
    multi_attempt_rate: 58.3,
    multi_attempt_denominator: 12,
    workaround_rate: 58.3,
    manual_scroll_rate: 41.7,
    unknown_outcome_count: 0,
    evidence_strength: "moderate",
    observed_consequence: "Financial inconvenience (lost receipts) or lost utility data.",
    root_cause_hypothesis: "Standard photo embedding treats screenshots as general visual scenes rather than text documents.",
    alternative_explanations: "Users deleting screenshots prematurely.",
    potential_ai_leverage: "Specialized OCR + layout understanding model for functional imagery.",
    uncertainty: "OCR processing cost at massive photo library scale.",
    generated_at: "2026-09-28T00:00:00Z",
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
  },
];

export const MOCK_EPISODES: RetrievalEpisode[] = [
  {
    id: "ep-001",
    record_id: "rec-001",
    visual_item_type: "photo",
    retrieval_goal: "Photo of a vintage coffee machine in a cafe in Lisbon",
    why_user_needs_item: "Recommend coffee machine model to a friend opening a cafe",
    outcome: "failure",
    impact_type: "functional",
    urgency: "low",
    frustration_level: "high",
    consequence: "Could not provide recommendation, gave up after 40 minutes",
    rationale_summary: "User remembered visual chrome details and country, but forgot cafe name and exact year.",
    extraction_confidence: 0.94,
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
    extracted_at: "2026-09-20T12:00:00Z",
  },
  {
    id: "ep-002",
    record_id: "rec-002",
    visual_item_type: "screenshot",
    retrieval_goal: "Screenshot of a handwritten pasta dough recipe from grandmother's notebook",
    why_user_needs_item: "Cook Sunday dinner for family using grandmother's recipe",
    outcome: "failure",
    impact_type: "emotional",
    urgency: "high",
    frustration_level: "extreme",
    consequence: "Had to use generic online recipe instead of family heirloom recipe",
    rationale_summary: "OCR failed on cursive handwriting on yellowed notebook paper screenshot.",
    extraction_confidence: 0.96,
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
    extracted_at: "2026-09-21T15:30:00Z",
  },
  {
    id: "ep-003",
    record_id: "rec-003",
    visual_item_type: "photo",
    retrieval_goal: "Group photo at friend's backyard birthday barbecue with sparklers at dusk",
    why_user_needs_item: "Post on friend's birthday social media post",
    outcome: "partial_success",
    impact_type: "emotional",
    urgency: "medium",
    frustration_level: "moderate",
    consequence: "Found photo after cross-referencing Instagram date for 15 minutes",
    rationale_summary: "User misremembered 2021 instead of 2020, but social cue enabled workaround.",
    extraction_confidence: 0.91,
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
    extracted_at: "2026-09-22T18:00:00Z",
  },
  {
    id: "ep-004",
    record_id: "rec-004",
    visual_item_type: "document",
    retrieval_goal: "Picture of the serial number sticker on the back of router",
    why_user_needs_item: "Provide ISP support with modem hardware MAC address",
    outcome: "failure",
    impact_type: "functional",
    urgency: "high",
    frustration_level: "high",
    consequence: "Had to physically crawl behind heavy entertainment center",
    rationale_summary: "Query 'router sticker' did not match barcode text.",
    extraction_confidence: 0.95,
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
    extracted_at: "2026-09-23T11:20:00Z",
  },
  {
    id: "ep-005",
    record_id: "rec-005",
    visual_item_type: "photo",
    retrieval_goal: "Sunset landscape photos over mountain ridge during hiking trip",
    why_user_needs_item: "Order framed print for living room wall",
    outcome: "success",
    impact_type: "emotional",
    urgency: "low",
    frustration_level: "low",
    consequence: "Found photo successfully via interactive map zoom",
    rationale_summary: "Spatial map search succeeded where text query failed.",
    extraction_confidence: 0.98,
    model_version: "gemini-3.8-flash",
    prompt_version: "2.1",
    schema_version: "2.1",
    extracted_at: "2026-09-24T14:10:00Z",
  },
];
